name: hsma_mab
channels:
  - defaults
  - conda-forge
dependencies:
  - jupyterlab=2.1.2
  - matplotlib=3.2.1
  - notebook=6.0.3
  - numpy=1.18.1
  - pandas=1.0.3
  - pip=20.0.2
  - python=3.7.7
  - pyqt=5.9.2
  - qt=5.9.7
  - spyder=4.1.5
  - pip:
    - seaborn==0.10.0
